apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-trioapp-dev
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
  annotations:
    codefresh.io/product: demo-trioapp
spec:
  project: default
  destination:
    name: in-cluster
    namespace: demo-dev
  source:
    path: demo-applications/trioapp-dev
    repoURL: https://github.com/hirotaka-suzuki/codefresh-quickstart-demo
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=false
      - ServerSideApply=true
      - RespectIgnoreDifferences=false
