gitops-runtime:
  global:
    codefresh:
      accountId: 68256d0fec78a3a004910d3e
      userToken:
        secretKeyRef:
          name: codefresh-user-token
          key: token
    runtime:
      name: codefresh
